# Generated by Django 4.0.6 on 2023-01-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_value',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
