# Generated by Django 4.1.4 on 2023-01-23 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=200)),
                ('total_cheer', models.PositiveIntegerField(default=0)),
                ('cur_cheer', models.PositiveIntegerField(default=0)),
                ('is_created', models.BooleanField(default=False)),
                ('image', models.CharField(choices=[('MONKEY', 'MONKEY'), ('MOUSE', 'MOUSE'), ('RABBIT', 'RABBIT'), ('SQUIRREL', 'SQUIRREL'), ('GOAT', 'GOAT'), ('BIRD', 'BIRD')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
