# Generated by Django 4.0.3 on 2023-01-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('total_cheer', models.PositiveIntegerField()),
                ('cur_cheer', models.PositiveIntegerField()),
                ('is_created', models.BooleanField(default=False)),
                ('image', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charms', to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
