# Generated by Django 4.1.4 on 2023-02-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charms', '0002_alter_charm_total_cheer'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='image_back',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charm',
            name='image_front',
            field=models.URLField(blank=True, null=True),
        ),
    ]
