# Generated by Django 4.0.6 on 2023-01-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_username'),
        ('charms', '0002_alter_charm_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charms', to='accounts.user'),
        ),
    ]
