# Generated by Django 4.1.4 on 2023-01-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('nickname', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('charm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheer', to='charms.charm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
